site_name: Ibai Web Page
site_author: Ibai García Arias
site_url: https://ibai-garcia.github.io


# Tema Material
extra_css:
  - styles/custom.css
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/images/IMG_9976.PNG            # Logo de la empresa
  favicon: assets/images/IMG_9976.PNG         # Favicon
  palette:
    #Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: dark blue
      accent: Light blue

    #Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: dark blue
 
  features:
    - navigation.tabs              # Pestañas en la parte superior
    - navigation.top               # Barra superior fija
    - content.code.copy            # Botón de copiar código
    - search.highlight             # Resalta resultados de búsqueda
    - toc.integrate                # TOC integrado en la página
  icon:
    repo: fontawesome/brands/github


# Extensiones de Markdown
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Inicio: index.md
  - Perfil Profesional: perfil.md
  - Educación: educacion.md
  - Experiencia: experiencia.md
  - Contacto: contacto.md
  - Currículum: cv.md


repo_url: https://github.com/ibai-garcia/Ibai-Garcia.github.io

